// Copyright (c) RightPeer Limited RightPeer
// RightPeer code distributed under the GPLv3 license, see COPYING file.

#ifndef RIGHTPEERVERSION_H
#define	RIGHTPEERVERSION_H

#define RIGHTPEER_VERSION_MAJOR     1
#define RIGHTPEER_VERSION_MINOR     0
#define RIGHTPEER_VERSION_REVISION  0
#define RIGHTPEER_VERSION_STAGE     2
#define RIGHTPEER_VERSION_BUILD     2

#define RIGHTPEER_PROTOCOL_VERSION 10008
#define RIGHTPEER_PROTOCOL_SUPPORTED "10004 - 10008, 20001"


#ifndef STRINGIZE
#define STRINGIZE(X) DO_STRINGIZE(X)
#endif

#ifndef DO_STRINGIZE
#define DO_STRINGIZE(X) #X
#endif

#define RIGHTPEER_BUILD_DESC_WITH_SUFFIX(maj, min, rev, build, suffix) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-" DO_STRINGIZE(suffix)

#define RIGHTPEER_BUILD_DESC_FROM_UNKNOWN(maj, min, rev, build) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build)


#define RIGHTPEER_BUILD_DESC "1.0 beta 2"
#define RIGHTPEER_BUILD_DESC_NUMERIC 10000202


#ifndef RIGHTPEER_BUILD_DESC
#ifdef BUILD_SUFFIX
#define RIGHTPEER_BUILD_DESC RIGHTPEER_BUILD_DESC_WITH_SUFFIX(RIGHTPEER_VERSION_MAJOR, RIGHTPEER_VERSION_MINOR, RIGHTPEER_VERSION_REVISION, RIGHTPEER_VERSION_BUILD, BUILD_SUFFIX)
#else
#define RIGHTPEER_BUILD_DESC RIGHTPEER_BUILD_DESC_FROM_UNKNOWN(RIGHTPEER_VERSION_MAJOR, RIGHTPEER_VERSION_MINOR, RIGHTPEER_VERSION_REVISION, RIGHTPEER_VERSION_BUILD)
#endif
#endif

#define RIGHTPEER_FULL_DESC(build, protocol) \
    "build " build " protocol " DO_STRINGIZE(protocol)


#ifndef RIGHTPEER_FULL_VERSION
#define RIGHTPEER_FULL_VERSION RIGHTPEER_FULL_DESC(RIGHTPEER_BUILD_DESC, RIGHTPEER_PROTOCOL_VERSION)
#endif


#define RIGHTPEER_VERSION_CODE_PROTOCOL_THIS              0
#define RIGHTPEER_VERSION_CODE_PROTOCOL_MIN               1
#define RIGHTPEER_VERSION_CODE_PROTOCOL_MIN_DOWNGRADE     2
#define RIGHTPEER_VERSION_CODE_PROTOCOL_MIN_NO_DOWNGRADE  3
#define RIGHTPEER_VERSION_CODE_PROTOCOL_FOR_RELEVANCE     4
#define RIGHTPEER_VERSION_CODE_BUILD                     16
#define RIGHTPEER_VERSION_CODE_MIN_VALID               1000

#endif	/* RIGHTPEERVERSION_H */

